#! /bin/sh
### BEGIN INIT INFO
# Provides:		tails-reconfigure-kexec
# Required-Start:	$local_fs
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:
# Short-Description:    Reconfigure kexec depending on running kernel
# Description:          Reconfigure kexec depending on running kernel
### END INIT INFO

. /lib/lsb/init-functions

PATH="/usr/local/bin:${PATH}"
KEXEC_CONF=/etc/default/kexec.d/wiperam

case "$1" in
  start)
	KERNEL_IMAGE=$(/usr/share/wiperam/get-bootinfo kernel)
	INITRD=$(/usr/share/wiperam/get-bootinfo initrd)
	echo "KERNEL_IMAGE=\"${KERNEL_IMAGE}\""   >  "$KEXEC_CONF"
	echo "INITRD=\"${INITRD}\""               >> "$KEXEC_CONF"
	if grep -qw debug=wipemem /proc/cmdline; then
	   echo 'APPEND="${APPEND} sdmemdebug=1"' >> "$KEXEC_CONF"
	else
	   echo 'APPEND="${APPEND} quiet"'        >> "$KEXEC_CONF"
	fi
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	rm -f "$KEXEC_CONF"
	;;
  *)
	echo "Usage: $0 start" >&2
	exit 3
	;;
esac
exit 0
