#! /bin/sh
### BEGIN INIT INFO
# Provides:		wiperam-reconfigure-memlockd
# Required-Start:	$local_fs $remote_fs
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:
# X-Start-Before:       memlockd
# Short-Description:    Reconfigure memlockd depending on running kernel
# Description:          Reconfigure memlockd depending on running kernel
### END INIT INFO

. /lib/lsb/init-functions

PATH="/usr/local/bin:${PATH}"
MEMLOCKD_CONF=/etc/memlockd.d/wiperam-runtime.cfg

case "$1" in
  start)
	# We're running *before* memlockd is started,
	# so we do not need to have it reload its configuration.
	/usr/share/wiperam/get-bootinfo kernel >  "$MEMLOCKD_CONF"
	/usr/share/wiperam/get-bootinfo initrd >> "$MEMLOCKD_CONF"
	;;
  stop|restart|reload|force-reload)
	rm -f "$MEMLOCKD_CONF"
	invoke-rc.d memlockd reload
	;;
  status)
	test -f "$MEMLOCKD_CONF"
	;;
  *)
	echo "Usage: $0 start" >&2
	exit 3
	;;
esac
exit 0
